### PR TITLE
Fix/bug edit event in profile screen

### LINKED ISSUE #340: fix bug edit event in profile screen
### Description:
Fix a bug in the userProfileScreen. Previously, the events in the userProfileScreen only have an edit button and not a join/leave button when the user is not the owner of the event. The issue also refactor the navigaiton of the EventEditionScreen by going to the screen that is before the EventEditionScreen in the stack. The issue also refactor the loading of the modification of the events by adding an automatic loading each time you come back to the screen after an edition of an event.

### PR DESCRIPTION
**Pull request by nodass**
### Description:
This pull request fixes bugs related to the edit event on the profile screen. Previously, all events displayed an edit button that did not work.

### Detailed changes:
- Add a callback that is triggered when the user clicks on the Edit button on the profile screen.
- Add a call to inform the EventViewModel of the current user, so that a Join/Leave button is displayed when the user is not the owner of the event, and an Edit button otherwise.
- Modify the navigation when leaving the event editing screen to return to the previous screen instead of going to the map.
- Add automatic loading of events on the profile screen and in the event screen, so that when the user modifies an event, they see their changes without having to leave and re-enter the screen.
- For the map, automatic loading was difficult to implement. To avoid strange behavior—where editing an event does not immediately show the modification when reopening the popup—the popup is now closed after editing.

Fix #340 

In MapScreen:

https://github.com/user-attachments/assets/32c5a505-ae26-455f-bacc-6132591ffff5

In ProfileScreen:

https://github.com/user-attachments/assets/9fd93ae6-a98c-4b17-b89d-1ad09d5783bb

In EventScreen:

https://github.com/user-attachments/assets/3b43721f-e020-4608-a0af-a207d0a910fc

### CODE REVIEW

File: app/src/main/java/com/android/universe/ui/event/EventScreen.kt [hunk 1]
```diff
@@ -67,7 +71,8 @@ fun EventScreen(
     viewModel: EventViewModel = viewModel(),
     onChatNavigate: (eventId: String, eventTitle: String) -> Unit = { _, _ -> },
     onCardClick: (eventId: String, eventLocation: Location) -> Unit = { _, _ -> },
-    onEditButtonClick: (uid: String, location: Location) -> Unit = { _, _ -> }
+    onEditButtonClick: (uid: String, location: Location) -> Unit = { _, _ -> },
+    navController: NavHostController = rememberNavController()
```
Comment (Corentin00) [inline app/src/main/java/com/android/universe/ui/event/EventScreen.kt]: Passing `NavHostController` into a screen composable is an architectural anti-pattern that tightly couples the UI to the navigation framework and breaks previews. Please remove it and handle the reload logic using `LifecycleEventObserver` or `DisposableEffect` observing the lifecycle.

Comment (nodass) [reply app/src/main/java/com/android/universe/ui/event/EventScreen.kt]: You're right. I knew it wasn't optimal, but I didn't know about LifecycleEventObserver and DisposableEffect, which is why I kept it that way. Thank you, I've changed it.

**Review by Corentin00 — APPROVED** [review]
