### PR TITLE
Fix Leave button on UserProfileScreen

### LINKED ISSUE #368: Fix Leave button on UserProfileScreen

### PR DESCRIPTION
**Pull request by AdeSolorio**
## Description
This pull request introduces a new unified method for toggling a user's participation in events and refactors the event participation logic across the codebase to use this method. It also updates the UI components and their interactions to work with the new approach. 

## Changes
- Added a new method `toggleEventParticipation(eventId: String, userId: String)` to the `EventRepository` interface and implemented it in both `EventRepositoryFirestore` and `FakeEventRepository`. This method adds or removes a user from an event's participant list depending on their current status.
- Updated `EventViewModel` and `UserProfileViewModel` to use the new `toggleEventParticipation` method, replacing the previous manual participant management logic. 
- Refactored `EventCard` and related composables to remove direct dependencies on `EventViewModel`, instead passing explicit callbacks and ownership flags. This decouples UI components from specific view models and improves reusability. 
- Updated `UserProfileScreen` and its child composables to use the new participation logic and view model structure. 

Closes #368 

Known issues: The creator is not loaded correctly on `UserProfileScreen`, tried to fix it on this PR, but the change was too long.

> This description and comments on the PR were rewritten using AI

### CODE REVIEW

File: app/src/main/java/com/android/universe/ui/profile/UserProfileScreen.kt [hunk 1]
```diff
@@ -427,10 +429,11 @@ fun ProfileEventList(
                       horizontal = Dimensions.PaddingMedium, vertical = Dimensions.PaddingSmall)) {
                 EventCard(
                     event = eventUIState,
+                    onToggleEventParticipation = userProfileViewModel::joinOrLeaveEvent,
```
Comment (poujhh) [inline app/src/main/java/com/android/universe/ui/profile/UserProfileScreen.kt]: Passing down a whole viewmodel to simply pass one of its functions seems a bit overkill no ? 
Wouldn't it be better to simply make it a (String) -> Unit function passed down ?
